# Generated by Django 2.2.2 on 2019-06-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_ip', models.CharField(max_length=16)),
                ('client_ip', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
