---
# Create ec2 instance and add it to ansible inventory
- name: Create a sandbox instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keyname: devsecops
    instance_type: t2.micro
    security_group: devsecops-python
    image: ami-0be057a22c63962cb
    region: eu-west-2
    tagname: Name=DevSecOps

  tasks:
    - name: Upload public key to AWS
      ec2_key:
         name: "{{ keyname }}"
         key_material: "{{ lookup('file', '~/.ssh/{{ keyname }}.pub') }}"
         region: "{{ region }}"

    - name: Launch instance
      ec2:
         key_name: "{{ keyname }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-f97e5d90
         assign_public_ip: yes
         instance_tags: "{{tagname}}"
      register: ec2

    - name: Add new instance to hosts group for test
      local_action: lineinfile
                    dest="~/ansible_hosts"
                    regexp={{ item.public_ip }}
                    insertafter="[tstlaunched]"
                    line="{{ item.public_ip }}"
                    state=present
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      local_action: wait_for
                    host={{ item.public_ip }}
                    port=22
                    state=started
      with_items: "{{ ec2.instances }}"                    
