- name: adding elastic gpg key for metricbeat
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: adding the elastic repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    state: present
  
- name: installing metricbeat 
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes

  with_items:
    - apt-transport-https
    - metricbeat

- name: adding metricbeat to the startup programs
  service:
    name: metricbeat
    enabled: yes
  
  notify:
   - start metricbeat