- name: AWS Security Audit using Scout2
  hosts: localhost
  become: yes
  
  tasks:
    - name: installing python and pip
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      
      with_items:
        - python
        - python-pip
    
    - name: install aws scout2
      pip:
        name: awsscout2